### ISSUE TITLE
Javascript errors at run time

### ISSUE THREAD

**Issue by vielmetti** [harbur/kubernetic-issues#15]
![screen shot 2017-03-03 at 2 18 57 pm](https://cloud.githubusercontent.com/assets/35047/23565787/0407a38c-001d-11e7-9e41-5738eb498191.png)

This happens after I launch for the first time; otherwise all of the screens are blank. I'm not sure how to proceed, perhaps I missed an instruction for the "getting started" part of Kubernetic.

**Comment by spiddy** [comment]
Hi,

you certainly didn't miss any instructions, this is a bug. Do you have a working `kubectl` environment? try doing `kubectl get nodes` in your machine to make sure. Since Kubernetic uses `kubectl` configuration it needs it to be able to connect properly on your cluster.

We'll add some more checks on startup to make sure things are as expected on next releases.

In the meantime can you provide some info on your environment? Is it GCP cluster, AWS or on-premise?

**Comment by vielmetti** [comment]
I'm bringing up Kubernetes on my Mac for the first time, so while I have a working `kubectl` binary, it gives this answer for get nodes:

```
$ kubectl get nodes
the server doesn't have a resource type "nodes"
```

so obviously I have a bit of work to do. 

Eventually the target deployment for this is some mix of bare metal nodes - either a Raspberry Pi 2 ARMv8 cluster, or a set of ARMv8 multicore servers at Packet (their 2A type). It's the initial bootstrapping process to get a cluster working enough that I can use Kubernetic to manage it.

Thanks for all your help.

**Comment by vielmetti** [comment]
OK, I worked through the issue identified in https://github.com/kubernetes/minikube/issues/99 to get minikube up and running on my Mac, and now Kubernetic is colorful and not blank.

**Comment by spiddy** [comment]
Great, I'll close the issue as solved then.
